apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
    jenkins/jenkins-jenkins-agent: "true"
  namespace: jenkins
spec:
  containers:
  - name: docker
    image: docker
    imagePullPolicy: IfNotPresent
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    command:
    - sleep
    args:
    - 99d
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    - mountPath: /home/jenkins/agent
      name: workspace-volume
  - name: kubectl
    image: bitnami/kubectl:1.22
    imagePullPolicy: IfNotPresent
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    command:
    - sleep
    args:
    - 99d 
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    - mountPath: /home/jenkins/agent
      name: workspace-volume
  - name: helm
    image: alpine/helm:3.7.1
    imagePullPolicy: IfNotPresent
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    command:
    - sleep
    args:
    - 99d 
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    - mountPath: /home/jenkins/agent
      name: workspace-volume
  #dnsPolicy: "None"
  #dnsConfig:
  #  nameservers:
  #    - 8.8.8.8
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: dockersock
  - emptyDir: {}
    name: workspace-volume
