apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
    jenkins/jenkins-jenkins-agent: "true"
  namespace: jenkins
spec:
  #securityContext:
   # runAsUser: 1000
    #runAsGroup: 1000      
  serviceAccountName: aws-iam-ecr    
  containers:
  - name: docker
    image: 516250856443.dkr.ecr.us-east-2.amazonaws.com/jenkins-airflow:kube-aws-cli-tools
    imagePullPolicy: IfNotPresent
    env:
    - name: AWS_EC2_METADATA_DISABLED
      value: "true"
    - name: AWS_SDK_LOAD_CONFIG
      value: "true"
    securityContext:
      privileged: true      
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    command:
    - sleep
    args:
    - 99d
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    - mountPath: /home/jenkins/agent
      name: workspace-volume
  #dnsPolicy: "None"
  #dnsConfig:
  #  nameservers:
  #    - 8.8.8.8
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: dockersock
  - emptyDir: {}
    name: workspace-volume
